name: Build Firebase Config

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout the repo
      - uses: actions/checkout@v4

      # 2. Generate firebase.js from the template using secrets
      - name: Inject Firebase secrets
        run: |
          sed -e "s|__API_KEY__|${{ secrets.FIREBASE_API_KEY }}|g" \
              -e "s|__AUTH_DOMAIN__|${{ secrets.FIREBASE_AUTH_DOMAIN }}|g" \
              -e "s|__DATABASE_URL__|${{ secrets.FIREBASE_DATABASE_URL }}|g" \
              -e "s|__PROJECT_ID__|${{ secrets.FIREBASE_PROJECT_ID }}|g" \
              -e "s|__STORAGE_BUCKET__|${{ secrets.FIREBASE_STORAGE_BUCKET }}|g" \
              -e "s|__MESSAGING_SENDER_ID__|${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}|g" \
              -e "s|__APP_ID__|${{ secrets.FIREBASE_APP_ID }}|g" \
              -e "s|__MEASUREMENT_ID__|${{ secrets.FIREBASE_MEASUREMENT_ID }}|g" \
              firebase-config.js > firebase.js

      # 3. (Optional) Deploy or build your project
      - name: Show generated config (for verification)
        run: cat firebase.js

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v7
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./  # your HTML files are in the repo root
